// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: inference.proto

#include "inference.pb.h"
#include "inference.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace inference {

static const char* InferenceService_method_names[] = {
  "/inference.InferenceService/Predict",
};

std::unique_ptr< InferenceService::Stub> InferenceService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< InferenceService::Stub> stub(new InferenceService::Stub(channel, options));
  return stub;
}

InferenceService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Predict_(InferenceService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status InferenceService::Stub::Predict(::grpc::ClientContext* context, const ::inference::PredictRequest& request, ::inference::PredictResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::inference::PredictRequest, ::inference::PredictResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Predict_, context, request, response);
}

void InferenceService::Stub::async::Predict(::grpc::ClientContext* context, const ::inference::PredictRequest* request, ::inference::PredictResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::inference::PredictRequest, ::inference::PredictResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Predict_, context, request, response, std::move(f));
}

void InferenceService::Stub::async::Predict(::grpc::ClientContext* context, const ::inference::PredictRequest* request, ::inference::PredictResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Predict_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::inference::PredictResponse>* InferenceService::Stub::PrepareAsyncPredictRaw(::grpc::ClientContext* context, const ::inference::PredictRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::inference::PredictResponse, ::inference::PredictRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Predict_, context, request);
}

::grpc::ClientAsyncResponseReader< ::inference::PredictResponse>* InferenceService::Stub::AsyncPredictRaw(::grpc::ClientContext* context, const ::inference::PredictRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPredictRaw(context, request, cq);
  result->StartCall();
  return result;
}

InferenceService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      InferenceService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< InferenceService::Service, ::inference::PredictRequest, ::inference::PredictResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](InferenceService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::inference::PredictRequest* req,
             ::inference::PredictResponse* resp) {
               return service->Predict(ctx, req, resp);
             }, this)));
}

InferenceService::Service::~Service() {
}

::grpc::Status InferenceService::Service::Predict(::grpc::ServerContext* context, const ::inference::PredictRequest* request, ::inference::PredictResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace inference
#include <grpcpp/ports_undef.inc>

